#!/bin/bash

RED=$(tput setaf 1)
BLU=$(tput setaf 4)
GRN=$(tput setaf 2)
NC=$(tput sgr0)

cont(){
read -n 1 -s -r input
case "$input" in
  *)
    ;;
esac
}

clear
echo
echo "[You can press any button to advance the text forward by one line.]"
echo
echo "${GRN}[GREEN]${NC}: Heya, Cap'n. What can I do you for?"
cont
echo "${RED}[RED]${NC}: Good day, ${GRN}[GREEN]${NC}. I just need to collect some data for my status report."
cont
echo "${GRN}[GREEN]${NC}: As expected. Whaddya got for me?"
cont
echo "${RED}[RED]${NC}: First, assigned tasks and their progress. Let's hear it."
cont
echo "${GRN}[GREEN]${NC}: Diverting the power and recalibrating the distributors. About done with both, I'd say."
cont
echo "${RED}[RED]${NC}: Great. Anything you've seen today?"
cont
echo "${GRN}[GREEN]${NC}: The only thing I've seen other than sparks has been ${BLU}[BLUE]${NC}. Not for very long, though."
cont
echo "${RED}[RED]${NC}: Understood. That'll be all, then. Report to me when your tasks have been completed."
cont
echo "${GRN}[GREEN]${NC}: Later, Cap'n."

cat ../../clues/greenClue
cp ../../clues/greenClue pockets/foundClues/greenClue
echo "[${RED}[GREEN]'s Clue ${NC}has been found! You can access it at any time via the ${BLU}foundClues ${NC}directory in your pocket.]"

exit
