#!/bin/bash

RED=$(tput setaf 1)
BLU=$(tput setaf 4)
YLW=$(tput setaf 3)
CYN=$(tput setaf 6)
NC=$(tput sgr0)

cont(){
read -n 1 -s -r input
case "$input" in
  *)
    ;;
esac
}

clear
echo
echo "[You can press any button to advance the text forward by one line.]"
echo
echo "${CYN}[CYAN]${NC}: Yo, Captain."
cont
echo "${RED}[RED]${NC}: Hey, ${CYN}[CYAN]${NC}. Can you give some time for this status report?"
cont
echo "${CYN}[CYAN]${NC}: Yeah, yeah. No prob. Gimme a sec..."
cont
echo "${CYN}[CYAN]${NC} is aggressively tapping the keyboard. Eventually, something blips back."
cont
echo "${CYN}[CYAN]${NC}: Sorry 'bout that. Reactor's important 'n all. "
cont
echo "${RED}[RED]${NC}: No problems at all. Tasks and... I guess I don't really need to ask for completion?"
cont
echo "${CYN}[CYAN]${NC}: Reactor maintenance and... I was probably supposed to help ${YLW}[YELLOW]${NC} with scans and samples."
cont
echo "${RED}[RED]${NC}: I'll put reactor maintenance down as complete. See anything out of the ordinary today?"
cont
echo "${CYN}[CYAN]${NC}: Not particularly. I've kinda been zipping around everywhere trying to keep the reactor from blowing us all up. Haven't been able to focus on much else."
cont
echo "${CYN}[CYAN]${NC}: Funnily, ${BLU}[BLUE]${NC} was zipping around just about as much as I was. Not sure for what, though."
cont
echo "${RED}[RED]${NC}: Understood. Alright, I'll be seeing you around."
cont
echo "${CYN}[CYAN]${NC}: Yup yup. Bye Captain."

cat ../../clues/cyanClue
cp ../../clues/cyanClue pockets/foundClues/cyanClue
echo "[${RED}[CYAN]'s Clue ${NC}has been found! You can access it at any time via the ${BLU}foundClues ${NC}directory in your pocket.]"

exit
